version: "3"
services:
  nginx-react:
    image: siteup:latest
    container_name: siteup
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      NODE_ENV: production
